name: localize-type
region: nyc

static_sites:
  - name: localize-type-web
    github:
      repo: victor-bynd/localize-type
      branch: main
      deploy_on_push: true
    
    build_command: npm run build
    output_dir: dist
    
    environment_slug: node-js
    
    routes:
      - path: /
    
    # Enable SPA routing - all routes serve index.html
    catchall_document: index.html
