import React, { useMemo, useState } from 'react';
import { useTypo } from '../context/useTypo';
import { useFontStack } from '../hooks/useFontStack';

const ExportCSSModal = ({ onClose }) => {
    const {
        configuredLanguages,
        fontStyles,
        getEffectiveFontSettingsForStyle,
        getFontsForStyle,
        getPrimaryFontFromStyle,
        getPrimaryFontOverrideForStyle,
        // Unused variables removed
    } = useTypo();

    const { buildFallbackFontStackForStyle } = useFontStack();
    const [useLangAttribute, setUseLangAttribute] = useState(true);
    const [useUtilityClasses, setUseUtilityClasses] = useState(false);

    const generateCSS = useMemo(() => {
        let css = '/* Generated by Type Localizer */\n\n';

        // 1. Font Face Definitions
        css += '/* @font-face Definitions */\n';

        const processedFonts = new Set();

        Object.keys(fontStyles || {}).forEach(styleId => {
            const style = fontStyles[styleId];

            // Primary Font
            const primary = style.fonts?.find(f => f.type === 'primary');
            if (primary && primary.fontUrl && !processedFonts.has(`primary-${styleId}`)) {
                const primarySettings = getEffectiveFontSettingsForStyle(styleId, primary.id);

                const lineGap = (primarySettings?.lineGapOverride !== undefined && primarySettings.lineGapOverride !== '')
                    ? `  line-gap-override: ${primarySettings.lineGapOverride * 100}%;\n` : '';
                const ascent = (primarySettings?.ascentOverride !== undefined && primarySettings.ascentOverride !== '')
                    ? `  ascent-override: ${primarySettings.ascentOverride * 100}%;\n` : '';
                const descent = (primarySettings?.descentOverride !== undefined && primarySettings.descentOverride !== '')
                    ? `  descent-override: ${primarySettings.descentOverride * 100}%;\n` : '';

                css += `@font-face {\n  font-family: 'UploadedFont-${styleId}';\n  src: url('${primary.fontUrl}');\n${lineGap}${ascent}${descent}}\n\n`;
                processedFonts.add(`primary-${styleId}`);
            }

            // Fallback Fonts
            (style.fonts || []).forEach(font => {
                if ((font.type === 'fallback' || font.type === 'primary') && (font.fontUrl || font.name)) {
                    const key = `fallback-${styleId}-${font.id}`;
                    if (processedFonts.has(key)) return;

                    const settings = getEffectiveFontSettingsForStyle(styleId, font.id);
                    let scale = settings?.scale ?? 100;
                    const sizeAdjust = (scale !== 100) ? `  size-adjust: ${scale}%;\n` : '';

                    const variationSettings = (font.isVariable || font.axes?.weight)
                        ? `  font-variation-settings: 'wght' ${settings?.weight ?? 400};\n` : '';

                    const lineGap = (settings?.lineGapOverride !== undefined && settings.lineGapOverride !== '')
                        ? `  line-gap-override: ${settings.lineGapOverride * 100}%;\n` : '';
                    const ascent = (settings?.ascentOverride !== undefined && settings.ascentOverride !== '')
                        ? `  ascent-override: ${settings.ascentOverride * 100}%;\n` : '';
                    const descent = (settings?.descentOverride !== undefined && settings.descentOverride !== '')
                        ? `  descent-override: ${settings.descentOverride * 100}%;\n` : '';

                    // If no URL (local font), assume local()
                    // If URL, use url() 
                    const src = font.fontUrl ? `url('${font.fontUrl}')` : `local('${font.name}')`;

                    css += `@font-face {\n  font-family: 'FallbackFont-${styleId}-${font.id}';\n  src: ${src};\n${sizeAdjust}${variationSettings}${lineGap}${ascent}${descent}}\n\n`;
                    processedFonts.add(key);
                }
            });
        });

        // 2. Language Classes
        css += '/* Language Specific Styles */\n';

        configuredLanguages.forEach(langId => {
            css += `\n/* Language: ${langId} */\n`;

            Object.keys(fontStyles || {}).forEach(styleId => {
                const parts = [];

                if (useLangAttribute) {
                    const baseSelector = `:lang(${langId})`;
                    if (styleId === 'primary') {
                        parts.push(baseSelector);
                    } else {
                        parts.push(`${baseSelector} .type-${styleId}`);
                        parts.push(`${baseSelector} ${styleId}`);
                    }
                }

                if (useUtilityClasses) {
                    const classSelector = `.lang-${langId}`;
                    if (styleId === 'primary') {
                        parts.push(classSelector);
                    } else {
                        parts.push(`${classSelector} .type-${styleId}`);
                        parts.push(`${classSelector} ${styleId}`);
                    }
                }

                if (parts.length === 0) return; // Skip if no selectors selected

                const selector = parts.join(', ');
                const stack = buildFallbackFontStackForStyle(styleId, langId);
                const fontFamily = stack.length > 0 ? stack.map(f => f.fontFamily).join(', ') : 'sans-serif';

                // Get primary settings/color
                const primaryFontOverride = getPrimaryFontOverrideForStyle(styleId, langId);
                let effectivePrimaryFont = null;
                const allFonts = getFontsForStyle(styleId);
                if (primaryFontOverride) {
                    effectivePrimaryFont = allFonts.find(f => f.id === primaryFontOverride);
                }
                if (!effectivePrimaryFont) {
                    effectivePrimaryFont = getPrimaryFontFromStyle(styleId);
                }

                const settings = getEffectiveFontSettingsForStyle(styleId, effectivePrimaryFont?.id || 'primary');

                // Check for overrides in primary settings
                const primaryHasOverrides = settings && (
                    (settings.lineGapOverride !== undefined && settings.lineGapOverride !== '') ||
                    (settings.ascentOverride !== undefined && settings.ascentOverride !== '') ||
                    (settings.descentOverride !== undefined && settings.descentOverride !== '')
                );

                // Check for overrides in fallback stack
                const fallbackHasOverrides = stack.some(f => {
                    const s = f.settings;
                    return s && (
                        (s.lineGapOverride !== undefined && s.lineGapOverride !== '') ||
                        (s.ascentOverride !== undefined && s.ascentOverride !== '') ||
                        (s.descentOverride !== undefined && s.descentOverride !== '')
                    );
                });

                const forceNormalLineHeight = primaryHasOverrides || fallbackHasOverrides;

                css += `${selector} {\n`;
                css += `  font-family: ${fontFamily};\n`;
                if (styleId === 'primary') {
                    if (forceNormalLineHeight) {
                        css += `  line-height: normal;\n`;
                    } else if (settings && settings.lineHeight) {
                        css += `  line-height: ${settings.lineHeight};\n`;
                    }
                }
                css += `}\n`;
            });
        });

        return css;

    }, [configuredLanguages, fontStyles, getEffectiveFontSettingsForStyle, getFontsForStyle, buildFallbackFontStackForStyle, getPrimaryFontFromStyle, getPrimaryFontOverrideForStyle, useLangAttribute, useUtilityClasses]);

    const handleDownload = () => {
        const blob = new Blob([generateCSS], { type: 'text/css' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = 'typography-settings.css';
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    };

    const handleCopy = () => {
        navigator.clipboard.writeText(generateCSS);
        // Show toast? relying on button text change for now
    };

    const [copyBtnText, setCopyBtnText] = useState('Copy to Clipboard');

    return (
        <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-slate-900/50 backdrop-blur-sm animate-fade-in">
            <div
                className="bg-white rounded-xl shadow-2xl w-full max-w-2xl h-[80vh] flex flex-col animate-scale-in"
                onClick={e => e.stopPropagation()}
            >
                {/* Header */}
                <div className="p-4 border-b border-slate-100 flex justify-between items-center bg-slate-50/50">
                    <div className="flex items-center gap-2">
                        <div className="p-1.5 rounded-lg bg-indigo-50 border border-indigo-100 text-indigo-600">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                                <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"></path>
                                <polyline points="7 10 12 15 17 10"></polyline>
                                <line x1="12" y1="15" x2="12" y2="3"></line>
                            </svg>
                        </div>
                        <h3 className="font-bold text-slate-800">Export CSS</h3>
                    </div>
                    <button
                        onClick={onClose}
                        className="p-1 rounded-lg text-slate-400 hover:text-slate-600 hover:bg-slate-100 transition-colors"
                    >
                        <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                            <path fillRule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clipRule="evenodd" />
                        </svg>
                    </button>
                </div>

                {/* Content */}
                <div className="flex-1 overflow-hidden flex flex-col p-0">
                    <div className="bg-amber-50 border-b border-amber-100 p-3 text-xs text-amber-800 flex items-start gap-2">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" className="w-4 h-4 shrink-0 mt-0.5">
                            <path fillRule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clipRule="evenodd" />
                        </svg>
                        <p>
                            <strong>Note:</strong> The font URLs point to temporary local references and need to be updated for production.
                        </p>
                    </div>

                    {/* Options Toolbar */}
                    <div className="px-4 py-3 bg-slate-50 border-b border-slate-100 flex items-center gap-6">
                        <label className="flex items-center gap-2 cursor-pointer group">
                            <div className={`w-4 h-4 rounded border flex items-center justify-center transition-colors ${useLangAttribute ? 'bg-indigo-600 border-indigo-600' : 'bg-white border-slate-300 group-hover:border-indigo-400'}`}>
                                {useLangAttribute && <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" className="w-3 h-3 text-white"><path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" /></svg>}
                            </div>
                            <input type="checkbox" className="hidden" checked={useLangAttribute} onChange={(e) => setUseLangAttribute(e.target.checked)} />
                            <span className="text-xs font-semibold text-slate-700 select-none">Attribute Selector <code>:lang()</code></span>
                        </label>

                        <label className="flex items-center gap-2 cursor-pointer group">
                            <div className={`w-4 h-4 rounded border flex items-center justify-center transition-colors ${useUtilityClasses ? 'bg-indigo-600 border-indigo-600' : 'bg-white border-slate-300 group-hover:border-indigo-400'}`}>
                                {useUtilityClasses && <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" className="w-3 h-3 text-white"><path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" /></svg>}
                            </div>
                            <input type="checkbox" className="hidden" checked={useUtilityClasses} onChange={(e) => setUseUtilityClasses(e.target.checked)} />
                            <span className="text-xs font-semibold text-slate-700 select-none">Utility Class <code>.lang-code</code></span>
                        </label>
                    </div>

                    <div className="flex-1 overflow-auto bg-slate-900 p-4">
                        <pre className="font-mono text-xs text-slate-300 whitespace-pre-wrap font-ligatures-none">
                            {generateCSS}
                        </pre>
                    </div>
                </div>

                {/* Footer */}
                <div className="p-4 border-t border-slate-100 bg-slate-50 flex justify-between items-center gap-3">
                    <button
                        onClick={onClose}
                        className="px-4 py-2 text-xs font-bold text-slate-600 hover:text-slate-800 hover:bg-slate-200 rounded-lg transition-colors"
                    >
                        Close
                    </button>
                    <div className="flex gap-2">
                        <button
                            onClick={() => {
                                handleCopy();
                                setCopyBtnText('Copied!');
                                setTimeout(() => setCopyBtnText('Copy to Clipboard'), 2000);
                            }}
                            className="px-4 py-2 text-xs font-bold text-indigo-600 bg-indigo-50 border border-indigo-100 hover:bg-indigo-100 rounded-lg transition-colors flex items-center gap-2"
                        >
                            <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                                <rect x="9" y="9" width="13" height="13" rx="2" ry="2"></rect>
                                <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path>
                            </svg>
                            {copyBtnText}
                        </button>
                        <button
                            onClick={handleDownload}
                            className="px-4 py-2 text-xs font-bold text-white bg-indigo-600 hover:bg-indigo-700 rounded-lg transition-colors flex items-center gap-2"
                        >
                            <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                                <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"></path>
                                <polyline points="7 10 12 15 17 10"></polyline>
                                <line x1="12" y1="15" x2="12" y2="3"></line>
                            </svg>
                            Download CSS
                        </button>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default ExportCSSModal;
